services:
  website:
    build:
      context: .
      args:
        # make sure to have this environment variable set in your .env file
        HUGO_BASEURL: ${HUGO_BASEURL}

    container_name: hugo-site
    restart: unless-stopped

    ports:
      - "8002:80"